import type { ChatTheme } from './types'

export const lightTheme: ChatTheme = {
  colors: {
    background: '#ffffff',
    surface: '#ffffff',
    border: '#e2e8f0',
    text: '#0f172a',
    textSecondary: '#475569',
    primary: '#2563eb',
    onPrimary: '#ffffff',
    danger: '#dc2626',
    codeBackground: '#0f172a',
    codeHeader: '#1e293b',
    codeText: '#e2e8f0',
    userBubble: '#ececec',
    userBubbleText: '#0f172a',
    assistantBubble: '#ffffff',
    systemBubble: '#f1f5f9',
    unreadBadge: '#dc2626',
    composerSurface: '#ffffff',
    composerInput: '#ffffff',
    composerBorder: '#d9d9e3',
    sendDisabled: '#e0e0e0',
    sendBackground: '#0f172a',
    sendForeground: '#ffffff',
    controlSurface: '#2563eb',
    focus: '#2563eb',
  },
  radii: {
    bubbleRadius: 18,
    composerRadius: 24,
    controlRadius: 20,
  },
  layout: {
    readingColumnWidth: 540,
    composerWidth: 650,
    sidePadding: 16,
  },
  spacing: {
    bubbleMarginH: 0,
    bubbleMarginV: 12,
    composerPaddingH: 12,
    composerPaddingV: 8,
    composerBottomGap: 16,
    paragraphGap: 8,
  },
  typography: {
    messageTextSize: 16,
    messageLineHeight: 24,
    messageWeight: '400',
    composerTextSize: 16,
    composerLineHeight: 24,
    controlTextSize: 14,
    controlLineHeight: 20,
    controlWeight: '500',
    captionTextSize: 12,
    captionLineHeight: 16,
    captionWeight: '600',
    headingWeight: '600',
  },
}

export const darkTheme: ChatTheme = {
  colors: {
    background: '#0f172a',
    surface: '#1e293b',
    border: '#334155',
    text: '#f1f5f9',
    textSecondary: '#94a3b8',
    primary: '#3b82f6',
    // Dark text on the primary-colored controls: white on #3b82f6 measures
    // 3.68:1, below the 4.5:1 normal-text requirement (research R4).
    onPrimary: '#0f172a',
    // #f87171 keeps 4.5:1 on the dark surfaces when used as text (research R4).
    danger: '#f87171',
    codeBackground: '#020617',
    codeHeader: '#0f172a',
    codeText: '#e2e8f0',
    userBubble: '#343536',
    userBubbleText: '#f1f5f9',
    assistantBubble: '#1e293b',
    systemBubble: '#1e293b',
    unreadBadge: '#ef4444',
    composerSurface: '#1e293b',
    composerInput: '#1e293b',
    composerBorder: '#3f3f46',
    sendDisabled: '#3f3f46',
    sendBackground: '#ffffff',
    sendForeground: '#0f172a',
    controlSurface: '#3b82f6',
    focus: '#60a5fa',
  },
  radii: {
    bubbleRadius: 18,
    composerRadius: 24,
    controlRadius: 20,
  },
  layout: {
    readingColumnWidth: 540,
    composerWidth: 650,
    sidePadding: 16,
  },
  spacing: {
    bubbleMarginH: 0,
    bubbleMarginV: 12,
    composerPaddingH: 12,
    composerPaddingV: 8,
    composerBottomGap: 16,
    paragraphGap: 8,
  },
  typography: {
    messageTextSize: 16,
    messageLineHeight: 24,
    messageWeight: '400',
    composerTextSize: 16,
    composerLineHeight: 24,
    controlTextSize: 14,
    controlLineHeight: 20,
    controlWeight: '500',
    captionTextSize: 12,
    captionLineHeight: 16,
    captionWeight: '600',
    headingWeight: '600',
  },
}

export const lightHighContrastTheme: ChatTheme = {
  colors: {
    background: '#ffffff',
    surface: '#ffffff',
    border: '#000000',
    text: '#000000',
    textSecondary: '#000000',
    primary: '#000000',
    onPrimary: '#ffffff',
    danger: '#a00000',
    codeBackground: '#000000',
    codeHeader: '#000000',
    codeText: '#ffffff',
    userBubble: '#000000',
    userBubbleText: '#ffffff',
    assistantBubble: '#ffffff',
    systemBubble: '#ffffff',
    unreadBadge: '#000000',
    composerSurface: '#ffffff',
    composerInput: '#ffffff',
    composerBorder: '#000000',
    sendDisabled: '#767676',
    sendBackground: '#000000',
    sendForeground: '#ffffff',
    controlSurface: '#000000',
    focus: '#000000',
  },
  radii: {
    bubbleRadius: 12,
    composerRadius: 18,
    controlRadius: 20,
  },
  layout: {
    readingColumnWidth: 540,
    composerWidth: 650,
    sidePadding: 16,
  },
  spacing: {
    bubbleMarginH: 0,
    bubbleMarginV: 12,
    composerPaddingH: 12,
    composerPaddingV: 8,
    composerBottomGap: 16,
    paragraphGap: 8,
  },
  typography: {
    messageTextSize: 16,
    messageLineHeight: 24,
    messageWeight: '400',
    composerTextSize: 16,
    composerLineHeight: 24,
    controlTextSize: 14,
    controlLineHeight: 20,
    controlWeight: '500',
    captionTextSize: 12,
    captionLineHeight: 16,
    captionWeight: '600',
    headingWeight: '600',
  },
}

export const darkHighContrastTheme: ChatTheme = {
  colors: {
    background: '#000000',
    surface: '#000000',
    border: '#ffffff',
    text: '#ffffff',
    textSecondary: '#e6e6e6',
    primary: '#ffffff',
    onPrimary: '#000000',
    danger: '#ff7b72',
    codeBackground: '#000000',
    codeHeader: '#1a1a1a',
    codeText: '#ffffff',
    userBubble: '#ffffff',
    userBubbleText: '#000000',
    assistantBubble: '#000000',
    systemBubble: '#000000',
    unreadBadge: '#ffffff',
    composerSurface: '#000000',
    composerInput: '#000000',
    composerBorder: '#ffffff',
    sendDisabled: '#767676',
    sendBackground: '#ffffff',
    sendForeground: '#000000',
    controlSurface: '#ffffff',
    focus: '#ffffff',
  },
  radii: {
    bubbleRadius: 12,
    composerRadius: 18,
    controlRadius: 20,
  },
  layout: {
    readingColumnWidth: 540,
    composerWidth: 650,
    sidePadding: 16,
  },
  spacing: {
    bubbleMarginH: 0,
    bubbleMarginV: 12,
    composerPaddingH: 12,
    composerPaddingV: 8,
    composerBottomGap: 16,
    paragraphGap: 8,
  },
  typography: {
    messageTextSize: 16,
    messageLineHeight: 24,
    messageWeight: '400',
    composerTextSize: 16,
    composerLineHeight: 24,
    controlTextSize: 14,
    controlLineHeight: 20,
    controlWeight: '500',
    captionTextSize: 12,
    captionLineHeight: 16,
    captionWeight: '600',
    headingWeight: '600',
  },
}

export const baseThemes: Record<'light' | 'dark', ChatTheme> = {
  light: lightTheme,
  dark: darkTheme,
}

export const highContrastThemes: Record<'light' | 'dark', ChatTheme> = {
  light: lightHighContrastTheme,
  dark: darkHighContrastTheme,
}
